### ISSUE TITLE
__aiter__() doesn't await next_page()

### ISSUE THREAD

**Issue by txomon** [quantmind/pulsar-cloud#14]
I may be wrong, but shouldn't `__aiter__()` await `next_page()`?

https://github.com/quantmind/pulsar-cloud/blob/28d7518160c9f82daba2d02f03ebd08d9e7e89fb/cloud/asyncbotocore/paginate.py#L89

**Comment by lsbardel** [comment]
You are right I think, that code is not covered by tests either.
This needs to be tested.

**Comment by lsbardel** [comment]
Tested and fixed it. Thanks for reporting
