### ISSUE TITLE
Adapt botocore to be used with pulsar async http client

### ISSUE THREAD

**Issue by lsbardel** [quantmind/pulsar-cloud#4]
Botocore uses `requests` as their `http` client and therefore it is a blocking client.
Our initial implementation tried to patch the request session using pulsar `greenio` but results are not very good. using threading is another approach but it seems to have problem with the GIL (not sure why).

An alternative, far better approach, would be to modify botocore so that it can be used with and asynchronous `http` client which has certain API signatures.
The starting point for this ticket is the https://github.com/jettify/aiobotocore project.

**Comment by pkisztelinski** [comment]
@lsbardel 

[branch](https://github.com/pkisztelinski/pulsar-cloud/tree/issue_4)
